- name: create prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: create prometheus system user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false
    home: /var/lib/prometheus

- name: create directory
  file:
    path: "{{ item }}"
    state: directory   
  with_items:  
    - /etc/prometheus
    - /var/lib/prometheus
 
- name: unarchive prometheus 
  unarchive: 
   src: prometheus-2.36.2.linux-amd64.tar.gz
   dest: /tmp/

- name: copy prometheus and promtool binaries
  copy:
    src: "/tmp/prometheus-2.36.2.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    remote_src: yes    
  with_items:
    - prometheus
    - promtool
  notify:
    - restart prometheus     

- name: copy configs prometheus and promtool binaries
  copy:
    src: "/tmp/prometheus-2.36.2.linux-amd64/{{ item }}"
    dest: "/etc/prometheus/" 
    remote_src: yes     
  with_items:
    - consoles
    - console_libraries    
    - prometheus.yml
  notify:
    - restart prometheus     

- name: cp web config
  copy:
    src: "{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
  with_items:
    - web.yml
    - alert.rules
  notify:
    - restart prometheus     

- name: cp prometheus config
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
  notify:
    - restart prometheus 
    
- name: change owners
  file:
   name: "{{ item }}"
   recurse: yes
   owner: prometheus
   group: prometheus
  with_items:  
    - /etc/prometheus
    - /var/lib/prometheus
  notify:
    - restart prometheus 

- name: change owners binaries files
  file:
   name: "{{ item }}"
   recurse: no
   mode: 0755
   owner: prometheus
   group: prometheus
  with_items:     
    - /usr/local/bin/prometheus 
    - /usr/local/bin/promtool
  notify:
    - restart prometheus 

- name: copy conf service
  copy: 
   src: prometheus.service
   dest: /etc/systemd/system/prometheus.service
  notify:
    - restart prometheus 