resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [db_1]
    db1 ansible_host=${local.workspace[terraform.workspace].ip_address_db1}

    [db_2]
    db2 ansible_host=${local.workspace[terraform.workspace].ip_address_db2}

    [wordpress]
    app ansible_host=${local.workspace[terraform.workspace].ip_address_app}

    [gitlab_server]
    gitlab ansible_host=${local.workspace[terraform.workspace].ip_address_gitlab}

    [gitlab_runner]
    grunner ansible_host=${local.workspace[terraform.workspace].ip_address_grunner}

    [grafana]
    monitoring ansible_host=${local.workspace[terraform.workspace].ip_address_monitoring}

    [revers_proxy]
    reversproxy.ru  ansible_host=${local.workspace[terraform.workspace].internet_next_hop_address}

    [all:vars]    
    domain=${local.workspace[terraform.workspace].domain}
    app_ip=${local.workspace[terraform.workspace].ip_address_app}
    monitoring_ip=${local.workspace[terraform.workspace].ip_address_monitoring}
    gitlab_ip=${local.workspace[terraform.workspace].ip_address_gitlab}
    grunner_ip=${local.workspace[terraform.workspace].ip_address_grunner}
    proxy_ip=${local.workspace[terraform.workspace].internet_next_hop_address}
    db1_ip=${local.workspace[terraform.workspace].ip_address_db1}
    db2_ip=${local.workspace[terraform.workspace].ip_address_db2}
    gitlab_pass=${var.gitlab_pass}

   
    DOC
    
  filename = "./inventory-${terraform.workspace}"

  depends_on = [
    yandex_compute_instance.gitlab
  ]
}


