---

- name: install php
  apt: 
   name: "{{ item }}"
   state: present
  with_items:
  - php-mysql
  - php-fpm

- name: start php-fpm
  service:
   name: php7.4-fpm
   state: started
   enabled: yes