global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
 - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100','{{proxy_ip}}:9100','{{db1_ip}}:9100','{{db2_ip}}:9100','{{app_ip}}:9100','{{gitlab_ip}}:9100','{{grunner_ip}}:9100']
 
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'localhost:9093'

