---

- name: create alertmanager system group
  group:
    name: alertmanager
    system: true
    state: present

- name: create alertmanager system user
  user:
    name: alertmanager
    system: true
    shell: "/usr/sbin/nologin"
    group: alertmanager
    createhome: false
    home: /var/lib/alertmanager

- name: create directory
  file:
    path: "{{ item }}"
    state: directory   
  with_items:  
    - /etc/alertmanager
    - /var/lib/alertmanager
 
- name: unarchive alertmanager-0.24.0.linux-amd64
  unarchive: 
   src: alertmanager-0.24.0.linux-amd64.tar.gz
   dest: /tmp/

- name: copy alertmanager and amtool binaries
  copy:
    src: "/tmp/alertmanager-0.24.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    remote_src: yes    
  with_items:
    - alertmanager
    - amtool
  notify:
    - restart alertmanager   

- name: copy configs alertmanager 
  copy:
    src: "/tmp/alertmanager-0.24.0.linux-amd64/alertmanager.yml"
    dest: "/etc/alertmanager/alertmanager.yml" 
    remote_src: yes       

- name: cp web config
  copy:
    src: web.yml
    dest: /etc/alertmanager/web.yml 
  notify:
    - restart alertmanager   

- name: change owners
  file:
   name: "{{ item }}"
   recurse: yes
   owner: alertmanager
   group: alertmanager
  with_items:  
    - /etc/alertmanager
    - /var/lib/alertmanager
  notify:
    - restart alertmanager   

- name: change owners binaries files
  file:
   name: "{{ item }}"
   recurse: no
   mode: 0755
   owner: alertmanager
   group: alertmanager
  with_items:     
    - /usr/local/bin/alertmanager 
    - /usr/local/bin/amtool
  notify:
    - restart alertmanager   

- name: copy  conf.file service alertmanager
  copy: 
   src: alertmanager.service
   dest: /etc/systemd/system/alertmanager.service
  notify:
    - restart alertmanager 