---

- name: create node_exporter system group
  group:
    name: node_exporter
    system: true
    state: present

- name: create node_exporter system user
  user:
    name: node_exporter
    system: true
    shell: "/usr/sbin/nologin"
    group: node_exporter
    createhome: false   
 
- name: unarchive node_exporter-1.3.1.linux-amd64.tar
  unarchive: 
   src: node_exporter-1.3.1.linux-amd64.tar.gz
   dest: /tmp/

- name: copy node_exporter  binaries
  copy:
    src: "/tmp/node_exporter-1.3.1.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    remote_src: yes 
  notify:
    - restart node_exporter     
  
- name: change owners binaries files
  file:
   name: /usr/local/bin/node_exporter
   recurse: no
   mode: 0755
   owner: node_exporter
   group: node_exporter
  notify:
    - restart node_exporter   
 
- name: copy  conf.file service node_exporter
  copy: 
   src: node_exporter.service
   dest: /etc/systemd/system/node_exporter.service
  notify:
    - restart node_exporter 