
- name: copy sql_dump to target host
  copy: 
    src: dump.sql
    dest: /tmp/dump.sql

- name: Restore database wordpress
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: wordpress
    state: import
    target: /tmp/dump.sql