---

- name: Allow connections local network
  ansible.builtin.iptables:
    chain: INPUT
    source: 192.168.0.0/16
    jump: ACCEPT

- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "22"
      - "80"
      - "443"
    jump: ACCEPT

- name: Allow connections lookup
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: l0
    jump: ACCEPT

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow ssh jump
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "31337"       
    ctstate: NEW
    jump: ACCEPT

- name: Set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP


